name: NativeLibrary
description: Bindings to `headers/example.h`.
output: 'lib/generated_bindings_js.dart'
headers:
  entry-points:
    - 'native/include/example.h'
enums:
  as-int:
    include:
      - MyEnumAsInt