name: ffigen_js
description: ffigen, but for Javascript/WebAssembly interop bindings  
version: 0.0.3-pre
repository: https://github.com/nmfisher/ffigen_js

environment:
  sdk: ">=3.6.0-0 <4.0.0"

dependencies:
  collection: ^1.19.1
  logging: ^1.3.0
  package_config: ^2.2.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  yaml_edit: ^2.2.2
  quiver: ^3.2.2
  ffi: ^2.1.4
  cli_util: ^0.4.2